### ISSUE TITLE
GIT error when running npm install on windows

### ISSUE THREAD

**Issue by hchouhan** [johnpapa/pluralsight-gulp#17]
Hi,
I'm getting below error when I run npm install

```
42 error Windows_NT 6.3.9600
43 error argv "node" "C:\\Users\\Harish Chouhan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
44 error node v0.12.7
45 error npm  v2.11.3
46 error code ELIFECYCLE
47 error Pluralsight-Gulp@0.1.0 install: `bower install`
47 error Exit status 1
48 error Failed at the Pluralsight-Gulp@0.1.0 install script 'bower install'.
48 error This is most likely a problem with the Pluralsight-Gulp package,
48 error not with npm itself.
48 error Tell the author that this fails on your system:
48 error     bower install
48 error You can get their info via:
48 error     npm owner ls Pluralsight-Gulp
48 error There is likely additional logging output above.
49 verbose exit [ 1, true ]
```

**Comment by johnpapa** [comment]
do you have bower installed?

`npm install bower -g`

**Comment by tamilsweet** [comment]
Hi,
I have bower installed and I get the same error.

```
100 info install wiredep@2.2.2
101 info postinstall wiredep@2.2.2
102 info install Pluralsight-Gulp@0.1.0
103 verbose unsafe-perm in lifecycle true
104 info Pluralsight-Gulp@0.1.0 Failed to exec install script
105 verbose stack Error: Pluralsight-Gulp@0.1.0 install: `bower install`
105 verbose stack Exit status 1
105 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
105 verbose stack     at EventEmitter.emit (events.js:110:17)
105 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
105 verbose stack     at ChildProcess.emit (events.js:110:17)
105 verbose stack     at maybeClose (child_process.js:1015:16)
105 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
106 verbose pkgid Pluralsight-Gulp@0.1.0
107 verbose cwd E:\Learnings\pluralsight-gulp
108 error Windows_NT 6.1.7601
109 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
110 error node v0.12.7
111 error npm  v2.11.3
112 error code ELIFECYCLE
113 error Pluralsight-Gulp@0.1.0 install: `bower install`
113 error Exit status 1
114 error Failed at the Pluralsight-Gulp@0.1.0 install script 'bower install'.
114 error This is most likely a problem with the Pluralsight-Gulp package,
114 error not with npm itself.
114 error Tell the author that this fails on your system:
114 error     bower install
114 error You can get their info via:
114 error     npm owner ls Pluralsight-Gulp
114 error There is likely additional logging output above.
115 verbose exit [ 1, true ]
```

**Comment by tamilsweet** [comment]
After searching a while [found a solution](https://github.com/bower/bower/issues/50#issuecomment-18274305) for the issue.

There is a workaround that makes git always use https.

```
git config --global url."https://".insteadOf git://
```

**Comment by hchouhan** [comment]
@johnpapa running that command you suggested to install bower worked. Now am able to see the local site running. Thanks again.
