### ISSUE TITLE
Gulp-inject error for version 4.0.0

### ISSUE THREAD

**Issue by chsakell** [johnpapa/pluralsight-gulp#33]
It seems that the gulp-inject fails for **"gulp-inject": "^4.0.0"** while running the _wiredep_  task reporting for unexpected token (syntax error related to startTag) . If I switch to **"gulp-inject": "^1.1.1"** works fine. Any ideas?

**Comment by BioPhoton** [comment]
Same here... 

```
path\to\folder\node_modules\gulp-inject\src\inject\index.js:127
      startTag,
              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (path\to\folder\node_modules\gulp-inject\index.js:4:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by chsakell** [comment]
I figured it out.  As of gulp-inject v4.0.0, NodeJS v4 or above is required which means that you need to install NodeJS latest [version](https://nodejs.org/en/download/). After installing it works just fine.

**Comment by eliduhon** [comment]
I have node v4.4.5 installed and am receiving async callback errors I have been searching threads and I have found comments regarding the implementation of .stream and del and provider errors. more to come.
