### ISSUE TITLE
Cannot find module 'q'

### ISSUE THREAD

**Issue by mb2o** [johnpapa/pluralsight-gulp#7]
I get the following error message after running : bower install

module.js:340
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Mark\AppData\Roaming\npm\node_modules\bower\bin\bower:6:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by mb2o** [comment]
Never mind! I think it is an issue with my NPM. 
I just updated it yesterday and now it fails on all my projects.

Sorry for the inconvenience.

**Comment by johnpapa** [comment]
glad you found it

**Comment by hassanyousufx** [comment]
Hey can you tell me how you exactly solved this issue? I am running 'gulp' and it gets me the same error.

**Comment by spotshare-nick** [comment]
`npm install -g q`
